---
- name: Configure OCP day two tasks
  hosts: localhost
  become: false
  gather_facts: false
  
  pre_tasks:
# add check to see if python3 is installed
  - name: Set python3
    set_fact:
      ansible_python_interpreter: /usr/bin/python3

  - name: Set kubeconfig env var
    lineinfile:
      path: $HOME/.bashrc
      regexp: "^export KUBECONFIG"
      line: "export KUBECONFIG=$HOME/openstack-upi/auth/kubeconfig" 

  roles:
    - htpasswd
    - chrony
    - networkpolicy
