---
# tasks file for htpasswd

- name: Set python3
  set_fact:
    ansible_python_interpreter: /usr/bin/python3

#- name: Ensure the htpasswd utility is installed
#  yum:
#    name: 
#      - httpd-tools
#      - python-passlib
#    state: present

- name: Create htpasswd directory
  file:
    path: "{{ htpasswd_dir }}"
    state: directory

- name: Ensure htpasswd credentials are configured
  htpasswd:
    path: "{{ htpasswd_file_path }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ htpasswd_credentials }}"

#- name: Create OCP secret
#  shell: "oc create secret generic htpass-secret --from-file=htpasswd={{ htpasswd_file_path }} -n openshift-config"

- name: Create OCP secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'htpasswd-secret.yaml.j2') }}"

- name: Create OAuth CR for htpasswd
  k8s:
    state: present
    definition:
      apiVersion: config.openshift.io/v1
      kind: OAuth
      metadata:
        name: cluster
      spec:
        identityProviders:
        - name: my_htpasswd_provider
          mappingMethod: claim
          type: HTPasswd
          htpasswd:
            fileData:
              name: htpass-secret

- name: Add cluster-admin to admin user
  shell: "oc adm policy add-cluster-role-to-user cluster-admin admin"

#- name: Wait for oauth-openshift pod to redeploy
#  pause: 
#    seconds: 20
#
#- shell: "oc whoami --show-server"
#  register: api_server
#
#- name: Attempt to login as htpasswd user
#  shell: "oc login -u {{ item.name }} -p {{ item.password }} {{ api_server }}"
#  with_items: "{{ htpasswd_credentials }}"
